apiVersion: v1
kind: ConfigMap
metadata:
  name: customerservice-config
data:
  server.port: "8081"
  spring.datasource.url: jdbc:mysql://mysql/customerdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  spring.datasource.platform: mysql
  spring.datasource.initialization-mode: always
  spring.jpa.hibernate.ddl-auto: create
  management.endpoints.web.exposure.include: "*"
  jwt.issuer: Sales Order System