apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: sales-order-system-app
        image: 066203203749.dkr.ecr.eu-west-2.amazonaws.com/sales-order-system-app:1.0.0-SNAPSHOT
        ports:
        - containerPort: 80