apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  selector:
    matchLabels:
      app: productservice
  replicas: 3
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: 066203203749.dkr.ecr.eu-west-2.amazonaws.com/product-service:1.0.0-SNAPSHOT
        ports:
        - containerPorts: 8083
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: productservice-secret
              key: jwt.secret
        volumeMounts:
        - name:  app-config
          mountPath: "/deployments/config"
          readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: productservice-config
          items:
          - key: application.properties
            path: application.properties