apiVersion: v1
kind: Service
metadata:
  name: productservice-service
  labels:
    app: productservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: productservice

