apiVersion: v1
kind: Service
metadata:
  name: customerservice-service
  labels:
    app: customerservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: customerservice

