apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
spec:
  selector:
    matchLabels:
      app: orderservice
  replicas: 3
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: 066203203749.dkr.ecr.eu-west-2.amazonaws.com/order-service:1.0.0-SNAPSHOT
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: orderservice-secret
              key: jwt.secret
        volumeMounts:
        - name:  app-config
          mountPath: "/deployments/config"
          readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: orderservice-config
          items:
          - key: orderservice.properties
            path: orderservice.properties