apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
  labels:
    app: orderservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: orderservice

